sudo: required
services:
  - docker

before_install:
  - docker build -t otmarvonwien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true otmarvonwien/react-test npm test

after_success:
  - docker build -t otmarvonwien/multi-client ./client
  - docker build -t otmarvonwien/multi-nginx ./nginx
  - docker build -t otmarvonwien/multi-server ./server
  - docker build -t otmarvonwien/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push otmarvonwien/multi-client
  - docker push otmarvonwien/multi-nginx
  - docker push otmarvonwien/multi-server
  - docker push otmarvonwien/multi-worker

delpoy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-939268298574
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
