sudo: required
services:
  - docker

before_install:
  - docker build -t otmarvonwien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true otmarvonwien/react-test npm test

after_success:
  - docker build -t otmarvonwien/multi-client ./client
  - docker build -t otmarvonwien/multi-nginx ./nginx
  - docker build -t otmarvonwien/multi-server ./server
  - docker build -t otmarvonwien/multi-worker ./worker

deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: master
