sudo: required
services:
  - docker

before_install:
  - docker build -t otmarvonwien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true otmarvonwien/react-test npm test

#after_success:

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
